# Generated by Django 6.0.4 on 2026-06-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_alter_doctorconsultation_meeting_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineReminder',
        ),
    ]
