# Generated by Django 6.0.4 on 2026-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_appointment_status_alter_appointment_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500', max_length=1000, null=True),
        ),
    ]
